const rest = new Map();
rest.set("Name", "Classic Pasta House");
console.log(rest.get("Name"));
rest.set(1, "Dhaka, Bangladesh");
console.log(rest.set(2, "Bagha, Rajshahi"));
rest.set("Staff", ["Abir", "Shohag", "Shohan", "Tarek"]);
rest.set("Open", 11);
rest.set("closed", 23);
rest.set(true, "We are open  :D");
rest.set(false, "We are closed  :(");
console.log(rest.get(true));
console.log(rest.get(1));
const time = 8;
console.log(rest.get(time > rest.get("Open") && time < rest.get("Closed")));
rest.delete(2);
rest.set([1, 2], "Test");
// rest.clear();
const arr = [2, 3];
rest.set(arr, "Test2");
console.log(rest);
console.log(rest.size);
console.log(rest.get(arr));
